[package]
name = "Forsecjie"
version = "0.1.0"
cjc-version = "0.60.5"
output-type = "executable"
compile-option = "-ldl"

[dependencies]

[target.x86_64-unknown-linux-gnu]

[target.x86_64-unknown-linux-gnu.bin-dependencies]
path-option = ["./cangjie-stdx/linux_x86_64_llvm/static/stdx"]
